#!/bin/bash
# Warp9Net IPAM — First-time setup script
# Generates .env with random secrets

set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  echo "⚠️  .env already exists. Delete it first if you want to regenerate."
  exit 1
fi

JWT_SECRET=$(openssl rand -base64 32)
DB_PASSWORD=$(openssl rand -base64 18 | tr -d '=+/')
ROOT_PASSWORD=$(openssl rand -base64 18 | tr -d '=+/')

cat > "$ENV_FILE" << EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# MySQL
DB_HOST=db
DB_PORT=3306
DB_USER=ipam
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=ipam
MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}

# JWT (used for API auth tokens)
JWT_SECRET=${JWT_SECRET}

# API
PORT=3001
EOF

echo "✅ .env created with random secrets."
echo ""
echo "Default login:  admin@warp9studios.com / admin123"
echo "⚠️  Change the admin password after first login!"
echo ""
echo "To deploy:  docker compose up -d"
