CREATE DATABASE IF NOT EXISTS ipam;
USE ipam;

-- Users (replaces Supabase auth.users)
CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Profiles
CREATE TABLE IF NOT EXISTS profiles (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  display_name VARCHAR(255),
  avatar_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- VLANs
CREATE TABLE IF NOT EXISTS vlans (
  id CHAR(36) PRIMARY KEY,
  vlan_id INT NOT NULL UNIQUE,
  name VARCHAR(255) DEFAULT '',
  subnet VARCHAR(255) DEFAULT '',
  color VARCHAR(50) DEFAULT '#3B82F6',
  icon VARCHAR(50) DEFAULT 'network',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Devices
CREATE TABLE IF NOT EXISTS devices (
  id CHAR(36) PRIMARY KEY,
  vlan_id INT NOT NULL,
  ip_address VARCHAR(255) DEFAULT '',
  device_name VARCHAR(255) DEFAULT '',
  brand VARCHAR(255) DEFAULT '',
  model VARCHAR(255) DEFAULT '',
  docs TEXT DEFAULT (''),
  location VARCHAR(255) DEFAULT '',
  notes TEXT DEFAULT (''),
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (vlan_id) REFERENCES vlans(vlan_id) ON DELETE CASCADE
);

-- Rack Items
CREATE TABLE IF NOT EXISTS rack_items (
  id CHAR(36) PRIMARY KEY,
  device_id CHAR(36),
  start_u INT NOT NULL,
  u_size INT DEFAULT 1,
  label VARCHAR(255) DEFAULT '',
  notes TEXT DEFAULT (''),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE SET NULL
);

-- Cable Drops
CREATE TABLE IF NOT EXISTS cable_drops (
  id CHAR(36) PRIMARY KEY,
  label VARCHAR(255) DEFAULT '',
  location VARCHAR(255) DEFAULT '',
  category VARCHAR(255) DEFAULT '',
  switch_model VARCHAR(255) DEFAULT '',
  switch_port VARCHAR(255) DEFAULT '',
  notes TEXT DEFAULT (''),
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- PDU Outlets
CREATE TABLE IF NOT EXISTS pdu_outlets (
  id CHAR(36) PRIMARY KEY,
  outlet_number INT NOT NULL,
  device_name VARCHAR(255) DEFAULT '',
  notes TEXT DEFAULT (''),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Wireless Networks
CREATE TABLE IF NOT EXISTS wireless_networks (
  id CHAR(36) PRIMARY KEY,
  ssid VARCHAR(255) DEFAULT '',
  password VARCHAR(255) DEFAULT '',
  notes TEXT DEFAULT (''),
  is_hidden TINYINT(1) DEFAULT 0,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- App Settings
CREATE TABLE IF NOT EXISTS app_settings (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  site_name VARCHAR(255) DEFAULT 'Warp9 IPAM',
  page_title VARCHAR(255) DEFAULT 'IPAM',
  favicon_url TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- SMTP Settings
CREATE TABLE IF NOT EXISTS smtp_settings (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  smtp_host VARCHAR(255) DEFAULT '',
  smtp_port INT DEFAULT 587,
  smtp_username VARCHAR(255) DEFAULT '',
  smtp_password VARCHAR(255) DEFAULT '',
  from_email VARCHAR(255) DEFAULT '',
  from_name VARCHAR(255) DEFAULT '',
  use_tls TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Audit Log
CREATE TABLE IF NOT EXISTS audit_log (
  id CHAR(36) PRIMARY KEY,
  action VARCHAR(255) NOT NULL,
  entity_type VARCHAR(255) NOT NULL,
  entity_id CHAR(36),
  details JSON,
  performed_by CHAR(36),
  performed_by_email VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed default admin user (password: admin123)
INSERT INTO users (id, email, password_hash) VALUES
  ('00000000-0000-0000-0000-000000000001', 'admin@warp9studios.com', '$2b$10$dNqV4VmeJ4y0MMI2bWRJK.ZKvixXTVA3EpKekbM9kPVyOx7oXvhIi')
ON DUPLICATE KEY UPDATE email = email;

INSERT INTO profiles (id, user_id, display_name) VALUES
  ('00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'Admin')
ON DUPLICATE KEY UPDATE display_name = display_name;
